### ISSUE TITLE
Close fab when any of the icons is clicked.

### ISSUE THREAD

**Issue by Hoossayn** [Robbendebiene/freestyle_speed_dial#2]
i am using Tuple3 to make my own custom ui, clicking on any the icon and navigate to another screen, this weird behaviour captures below happens, the icon sits at the top left corner of the next screen 

my onPressed looks like 
<img width="512" alt="Screenshot 2023-03-18 at 19 31 27" src="https://user-images.githubusercontent.com/35276272/226128777-beb5423d-1a2e-493a-a24b-f5ea60c89375.png">

![Screenshot_20230318_191908](https://user-images.githubusercontent.com/35276272/226126733-c6ebb879-22b7-46fd-a027-dd3de210e3c6.png)

**Comment by Robbendebiene** [comment]
Can you please include a minimal example code?
Even the code of the speed dial widget builder and at which place in the widget hierarchy you are using it would help.

**Comment by Hoossayn** [comment]
<img width="552" alt="Screenshot 2023-03-19 at 11 19 01" src="https://user-images.githubusercontent.com/35276272/226168990-1d5c68c2-28d2-4608-9e53-449450197de8.png">
<img width="577" alt="Screenshot 2023-03-19 at 11 21 01" src="https://user-images.githubusercontent.com/35276272/226168999-42a19f57-620a-45b3-8a67-7446b6848590.png">
<img width="582" alt="Screenshot 2023-03-19 at 11 21 26" src="https://user-images.githubusercontent.com/35276272/226169001-c79b915b-23c1-4e40-a865-ab6837b3a6de.png">
<img width="608" alt="Screenshot 2023-03-19 at 11 21 50" src="https://user-images.githubusercontent.com/35276272/226169004-fe93f1ee-4233-46c6-89e5-ec9a0f32bd53.png">

@Robbendebiene i hope these helps, let me know if you need any more context

**Comment by Robbendebiene** [comment]
This happens because the `SpeedDialBuilder` internally adds the sub buttons to the nearest `Overlay`. The `MaterialApp` widget provides an `Overlay` which however is above the `Navigator`, wherefore the `Overlay` and its items will stay on he screen.

Not sure what would be the best way to deel with this from a package point of view.

You could add another layer/Overlay around your `Scaffold` like this to solve the problem:
```dart
  Widget build(BuildContext context) {
    return Overlay(
      initialEntries: [
        OverlayEntry(
          builder: (context) => Scaffold(
            floatingActionButton: SpeedDialBuilder(
              buttonAnchor: Alignment.topCenter,
              itemAnchor: Alignment.bottomCenter,
              buttonBuilder: (context, isActive, toggle) =>
                  FloatingActionButton(
                onPressed: toggle,
                child: AnimatedRotation(
                  duration: const Duration(milliseconds: 300),
                  curve: Curves.easeInOutCubicEmphasized,
                  turns: isActive ? 0.125 : 0,
                  child: const Icon(Icons.add),
                ),
              ),
              itemBuilder: (context, Tuple3<IconData, String, LayerLink> item,
                  i, animation) {
                return FractionalTranslation(
                  translation: Offset(0, -i.toDouble()),
                  child: ScaleTransition(
                    scale: animation,
                    child: FloatingActionButton.small(
                      onPressed: () {
                        Navigator.of(context).push(PageRouteBuilder(pageBuilder: (_, __, ___) => MyPage()));
                      },
                      child: Icon(item.item1),
                    ),
                  ),
                );
              },
              items: [
                Tuple3<IconData, String, LayerLink>(
                    Icons.hub, 'Hub', LayerLink()),
                Tuple3<IconData, String, LayerLink>(
                    Icons.track_changes, 'Track', LayerLink()),
                Tuple3<IconData, String, LayerLink>(
                    Icons.ice_skating_outlined, 'Ice', LayerLink())
              ],
            )
          )
        )
      ]
    );
  }

```

**Comment by Hoossayn** [comment]
thanks, this seem to fix the issue

**Comment by sookwalinga** [comment]
Worked for me too

**Comment by meet2711** [comment]
I tried the solution provided, it doesn't seem to work for me. Could you help @Robbendebiene ?
